stages:
  - test
  - documentation

services:
  - postgres:latest

.elixir-task:
  image: elixir:1.11.4-alpine
  cache:
    paths:
    - _build/
  before_script:
  - apk --update add postgresql-client git make g++
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

compilation:
  stage: test
  extends: .elixir-task
  script:
  - mix compile --force --warnings-as-errors

dialyzer:
  stage: test
  extends: .elixir-task
  script:
  - mix dialyzer

credo:
  stage: test
  extends: .elixir-task
  script:
  - mix credo --strict

test:
  stage: test
  extends: .elixir-task
  script:
  - mix test --trace --cover
  coverage: '/\d+.\d+\%\s+\|\s+Total/'
  variables:
    POSTGRES_DATABASE: boruta_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    MIX_ENV: test

pages:
  extends: .elixir-task
  stage: documentation
  script:
    - mix docs -f html
    - mv doc/ public/
  artifacts:
    paths:
      - public
  only:
    - master
